spring:
  application:
    name: pure-client
  security:
    oauth2:
      client:
        registration:
          keycloak-client:
            client-id: oauth2-client-credentials
            client-secret: S6ulK3OlfvWqvbruDWJ2ro2JkApastBXxMH6RwN4JM8yyhpuC2oPsPDknr1fUQChaOxmDvA2XrLkuVKpUhCE1H
            authorization-grant-type: client_credentials
            scope:
              - openid
        provider:
          keycloak-client:
            token-uri: http://localhost:8448/realms/oauth2-demos/protocol/openid-connect/token

service2:
  url: http://localhost:8082

server:
  port: 8081